(function(){
"use strict";
const DAY_KEYS=["mon","tue","wed","thu","fri","sat","sun"];
const DAY_SHORT={mon:"Mo",tue:"Di",wed:"Mi",thu:"Do",fri:"Fr",sat:"Sa",sun:"So"};
const DOW_TO_KEY=["sun","mon","tue","wed","thu","fri","sat"];
const DOW_SHORT=["So","Mo","Di","Mi","Do","Fr","Sa"];
const MONTH_NAMES=["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];
const BUNDESLAENDER={BW:"Baden-Württemberg",BY:"Bayern",BE:"Berlin",BB:"Brandenburg",HB:"Bremen",HH:"Hamburg",HE:"Hessen",MV:"Mecklenburg-Vorpommern",NI:"Niedersachsen",NW:"Nordrhein-Westfalen",RP:"Rheinland-Pfalz",SL:"Saarland",SN:"Sachsen",ST:"Sachsen-Anhalt",SH:"Schleswig-Holstein",TH:"Thüringen"};
const state={weekTours:Object.fromEntries(DAY_KEYS.map(k=>[k,0])),yearDays:[],publicMap:{},schoolMap:{},currentYear:null,currentState:"",currentView:"week",loading:false,generated:false};
const $=id=>document.getElementById(id);
function clampInt(v,mn,mx){const n=parseInt(v,10);return isNaN(n)?mn:Math.min(Math.max(n,mn),mx);}
function clampFloat(v,mn,mx){const n=parseFloat(v);return isNaN(n)?mn:Math.min(Math.max(n,mn),mx);}
const groupSize=()=>clampInt($("groupSize").value,1,9999);
const duration=()=>clampInt($("tourDuration").value,1,1440);
const vorlauf=()=>clampInt($("prepTime").value,0,120);
const nachlauf=()=>clampInt($("followTime").value,0,120);
const staffMin=()=>duration()+vorlauf()+nachlauf();
const wage=()=>clampFloat($("hourlyWage").value,0,9999);
const svFactor=()=>1+clampFloat($("svRate").value,0,100)/100;
const bufFactor=()=>1+clampFloat($("bufferRate").value,0,100)/100;
const priceAdult=()=>clampFloat($("priceAdult").value,0,9999);
const priceReduced=()=>clampFloat($("priceReduced").value,0,9999);
const avgPrice=()=>(priceAdult()+priceReduced())/2;
const levels=()=>({low:clampInt($("levelLow").value,0,99),medium:clampInt($("levelMedium").value,0,99),high:clampInt($("levelHigh").value,0,99)});
const levelPreset=k=>{const l=levels();return l[k]||0;};
function inferLevel(t){const l=levels();if(t<=0)return"none";if(t===l.low)return"low";if(t===l.medium)return"medium";if(t===l.high)return"high";return"custom";}
function classifyWeek(t,l){if(t<=0)return{key:"none",label:"–"};if(t>l.high)return{key:"over",label:"ÜBER HIGH"};if(t>=l.high)return{key:"high",label:"HIGH"};if(t>=l.medium)return{key:"medium",label:"MEDIUM"};if(t>=l.low)return{key:"low",label:"LOW"};return{key:"low",label:"< LOW"};}
function formatDuration(m){if(!m)return"0 h";const h=Math.floor(m/60),r=m%60;if(!h)return r+" min";if(!r)return h+" h";return h+" h "+r+" min";}
function formatHours(m){if(!m)return"0 h";const h=m/60;return(Number.isInteger(h)?h:h.toFixed(1).replace(".",","))+" h";}
function formatEuro(n){return n.toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function keyFor(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");}
function parseKey(k){const[y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d);}
function formatDate(d){return String(d.getDate()).padStart(2,"0")+"."+String(d.getMonth()+1).padStart(2,"0")+"."+d.getFullYear();}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function easterSunday(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,L=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*L)/451),mo=Math.floor((h+L-7*m+114)/31),dy=((h+L-7*m+114)%31)+1;return new Date(y,mo-1,dy);}
function getPublicHolidays(y){const e=easterSunday(y),map={},add=(d,n)=>{map[keyFor(d)]=n;},fx=(mo,dy,n)=>add(new Date(y,mo-1,dy),n),rel=(days,n)=>{const d=new Date(e);d.setDate(d.getDate()+days);add(d,n);};fx(1,1,"Neujahr");rel(-2,"Karfreitag");rel(1,"Ostermontag");fx(5,1,"Tag der Arbeit");rel(39,"Christi Himmelfahrt");rel(50,"Pfingstmontag");fx(10,3,"Tag der Deutschen Einheit");fx(12,25,"1. Weihnachtstag");fx(12,26,"2. Weihnachtstag");return map;}
async function fetchSchool(y,sc){if(!sc)return null;const sub="DE-"+sc;try{const r=await fetch("https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&languageIsoCode=DE&validFrom="+y+"-01-01&validTo="+y+"-12-31&subdivisionCode="+sub,{headers:{Accept:"application/json"}});if(r.ok)return{src:"oh",data:await r.json()};}catch(e){}try{const r2=await fetch("https://ferien-api.de/api/v1/holidays/"+sc+"/"+y);if(r2.ok)return{src:"fa",data:await r2.json()};}catch(e){}return null;}
function buildSchoolMap(resp){const map={};if(!resp||!resp.data)return map;const addR=(s,e,n)=>{const sd=parseKey(s.slice(0,10)),ed=parseKey(e.slice(0,10));for(let d=new Date(sd);d<=ed;d.setDate(d.getDate()+1)){const k=keyFor(d);if(!map[k])map[k]=n;else if(!map[k].includes(n))map[k]+=" · "+n;}};if(resp.src==="oh")(resp.data||[]).forEach(h=>{let n="Ferien";if(Array.isArray(h.name)){const de=h.name.find(x=>x.language==="DE")||h.name[0];if(de&&de.text)n=de.text;}addR(h.startDate,h.endDate,n);});else if(resp.src==="fa")(resp.data||[]).forEach(h=>{const s=(h.start||"").slice(0,10),e=(h.end||"").slice(0,10);if(s&&e)addR(s,e,h.name||"Ferien");});return map;}
// Musterwoche
function initTemplate(){const g=$("templateGrid");g.innerHTML="";DAY_KEYS.forEach(k=>{const d=document.createElement("div");d.className="tpl-day";d.innerHTML=`<label>${DAY_SHORT[k]}</label><input type="number" min="0" max="99" value="0" data-day="${k}" class="tpl-input"><div class="tpl-quick"><button type="button" class="q-low" data-day="${k}" data-lvl="low">LOW</button><button type="button" class="q-medium" data-day="${k}" data-lvl="medium">MED</button><button type="button" class="q-high" data-day="${k}" data-lvl="high">HIGH</button></div><div class="tpl-tag" data-day="${k}">–</div>`;g.appendChild(d);});g.querySelectorAll(".tpl-input").forEach(i=>{i.addEventListener("input",()=>{state.weekTours[i.dataset.day]=clampInt(i.value,0,99);renderWeek();});});g.querySelectorAll(".tpl-quick button").forEach(b=>{b.addEventListener("click",()=>{state.weekTours[b.dataset.day]=levelPreset(b.dataset.lvl);renderWeek();});});}
function updateAvgPrice(){const el=$("avgPriceDisplay");if(el)el.textContent=formatEuro(avgPrice());}
function renderWeek(){updateAvgPrice();const gs=groupSize(),sDur=staffMin(),w=wage(),sv=svFactor(),bf=bufFactor(),lvl=levels(),ap=avgPrice();let tt=0;const bk={none:0,low:0,medium:0,high:0,over:0};DAY_KEYS.forEach(k=>{const t=state.weekTours[k];const inp=document.querySelector(`.tpl-input[data-day="${k}"]`);if(inp&&parseInt(inp.value,10)!==t)inp.value=t;const tag=document.querySelector(`.tpl-tag[data-day="${k}"]`);const cls=classifyWeek(t,lvl);if(tag){tag.className="tpl-tag occ-"+cls.key;tag.textContent=cls.label;}tt+=t;bk[cls.key]=(bk[cls.key]||0)+1;});const hrs=tt*sDur/60;const cost=hrs*w;const revenue=tt*gs*ap;$("kpiTours").textContent=tt;$("kpiVisitors").textContent=tt*gs;$("kpiHours").textContent=formatDuration(tt*sDur);$("kpiLoad").textContent=avgLoadLabel(bk);$("kpiCost").textContent=formatEuro(cost);$("kpiCostFull").textContent=formatEuro(cost*sv*bf);$("kpiRevenue").textContent=formatEuro(revenue);}
function avgLoadLabel(b){const w={low:1,medium:2,high:3,over:4};let s=0,c=0;for(const k of Object.keys(w)){s+=(b[k]||0)*w[k];c+=b[k]||0;}if(!c)return"–";const a=s/c;if(a>=3.5)return"ÜBER HIGH";if(a>=2.5)return"HIGH";if(a>=1.5)return"MEDIUM";return"LOW";}
// Jahr
async function generateYear(){if(state.loading)return;const y=clampInt($("yearSelect").value,2000,2099),sc=$("stateSelect").value;state.currentYear=y;state.currentState=sc;state.publicMap=getPublicHolidays(y);if(sc){setInfo("Lade Schulferien für "+BUNDESLAENDER[sc]+" "+y+" …","loading");state.loading=true;setButtonsDisabled(true);const resp=await fetchSchool(y,sc);state.schoolMap=buildSchoolMap(resp);state.loading=false;setButtonsDisabled(false);if(resp){const src=resp.src==="oh"?"openholidaysapi.org":"ferien-api.de";setInfo("Feiertage & Schulferien für "+BUNDESLAENDER[sc]+" "+y+" geladen ("+src+").","success");}else{setInfo("Schulferien-API nicht erreichbar – nur bundesweite Feiertage.","warning");}}else{state.schoolMap={};setInfo("Kein Bundesland gewählt – nur bundesweite Feiertage.","");}buildYearDays(y);applyTemplateToYear(false);renderYearTable();renderYearKpis();renderMonthly();state.generated=true;$("exportActions").hidden=false;}
function buildYearDays(y){state.yearDays=[];const end=new Date(y+1,0,1);for(let d=new Date(y,0,1);d<end;d.setDate(d.getDate()+1)){const k=keyFor(d);state.yearDays.push({key:k,date:new Date(d),dow:d.getDay(),ph:state.publicMap[k]||"",sh:state.schoolMap[k]||"",tours:0,level:"none",notes:""});}}
function applyTemplateToYear(upd){if(!state.yearDays.length){generateYear();return;}const ex=$("excludeHolidays").checked;state.yearDays.forEach(d=>{const wk=DOW_TO_KEY[d.dow];d.tours=(ex&&d.ph)?0:(state.weekTours[wk]||0);d.level=inferLevel(d.tours);});if(upd!==false){renderYearTable();renderYearKpis();renderMonthly();}}
function renderYearTable(){const tb=$("dayTableBody");tb.innerHTML="";const f=document.createDocumentFragment();let lm=-1;state.yearDays.forEach(d=>{const m=d.date.getMonth();if(m!==lm){lm=m;const mr=document.createElement("tr");mr.className="month-header";mr.innerHTML=`<td colspan="8">${MONTH_NAMES[m]} ${d.date.getFullYear()}</td>`;f.appendChild(mr);}f.appendChild(buildRow(d));});tb.appendChild(f);state.yearDays.forEach(updateRow);}
function buildRow(day){const tr=document.createElement("tr");tr.dataset.key=day.key;if(day.dow===0||day.dow===6)tr.classList.add("weekend");if(day.ph)tr.classList.add("holiday");if(day.sh)tr.classList.add("school-holiday");tr.innerHTML=`<td>${formatDate(day.date)}</td><td>${DOW_SHORT[day.dow]}</td><td class="holiday-cell">${day.ph?`<span class="ph">${escapeHtml(day.ph)}</span>`:""}${day.ph&&day.sh?"<br>":""}${day.sh?`<span class="sh">${escapeHtml(day.sh)}</span>`:""}</td><td><select class="occupancy-select" data-role="level"><option value="none">Keine</option><option value="low">LOW</option><option value="medium">MEDIUM</option><option value="high">HIGH</option><option value="custom">Manuell</option></select></td><td><input type="number" min="0" max="99" class="tour-input" data-role="tours"></td><td class="visitors-cell" data-role="guests">0</td><td class="visitors-cell hours-cell" data-role="staff">0 h</td><td><input type="text" class="note-input" data-role="notes" placeholder="Notizen"></td>`;tr.querySelector("[data-role=level]").addEventListener("change",e=>{day.level=e.target.value;if(day.level==="none")day.tours=0;else if(day.level!=="custom")day.tours=levelPreset(day.level);updateRow(day);renderYearKpis();renderMonthly();});tr.querySelector("[data-role=tours]").addEventListener("input",e=>{day.tours=clampInt(e.target.value,0,99);day.level=inferLevel(day.tours);updateRow(day);renderYearKpis();renderMonthly();});tr.querySelector("[data-role=notes]").addEventListener("input",e=>{day.notes=e.target.value;});return tr;}
function updateRow(day){const tr=document.querySelector(`tr[data-key="${day.key}"]`);if(!tr)return;const sl=tr.querySelector("[data-role=level]"),it=tr.querySelector("[data-role=tours]"),gc=tr.querySelector("[data-role=guests]"),sc=tr.querySelector("[data-role=staff]"),ni=tr.querySelector("[data-role=notes]");sl.value=day.level;sl.setAttribute("data-occ",day.level);if(parseInt(it.value,10)!==day.tours)it.value=day.tours;if(ni.value!==day.notes)ni.value=day.notes;gc.textContent=(day.tours*groupSize()).toString();sc.textContent=formatHours(day.tours*staffMin());}
function renderYearKpis(){let tt=0,ad=0;state.yearDays.forEach(d=>{tt+=d.tours;if(d.tours>0)ad++;});const gs=groupSize(),sDur=staffMin(),hrs=tt*sDur/60,w=wage(),sv=svFactor(),bf=bufFactor(),cost=hrs*w,ap=avgPrice(),revenue=tt*gs*ap,costFull=cost*sv*bf,profit=revenue-costFull;$("yearKpiTours").textContent=tt;$("yearKpiGuests").textContent=tt*gs;$("yearKpiHours").textContent=formatHours(tt*sDur);$("yearKpiDays").textContent=ad;$("yearKpiRevenue").textContent=formatEuro(revenue);$("yearKpiCost").textContent=formatEuro(cost);$("yearKpiCostFull").textContent=formatEuro(costFull);$("yearKpiProfit").textContent=formatEuro(profit);const pe=$("yearKpiProfit");if(pe)pe.style.color=profit>=0?"#a7f3d0":"#fca5a5";}
function getMonthlyStats(){const ms=Array.from({length:12},()=>({tours:0,guests:0,mins:0,days:0}));const sDur=staffMin();state.yearDays.forEach(d=>{const m=d.date.getMonth();ms[m].tours+=d.tours;ms[m].guests+=d.tours*groupSize();ms[m].mins+=d.tours*sDur;if(d.tours>0)ms[m].days++;});return ms;}
function renderMonthly(){const ms=getMonthlyStats(),g=$("monthlyGrid");g.innerHTML="";const w=wage(),sv=svFactor(),bf=bufFactor(),ap=avgPrice();ms.forEach((m,i)=>{const hrs=m.mins/60;const cost=hrs*w*sv*bf;const revenue=m.guests*ap;const diff=revenue-cost;const d=document.createElement("div");d.className="monthly-item";d.innerHTML=`<div class="month-name">${MONTH_NAMES[i]}</div><div class="month-value">${m.tours} Führungen</div><div class="month-sub">${m.guests} Gäste · ${m.days} Tage<br>${formatHours(m.mins)} · Personal: ${formatEuro(cost)}</div><div class="month-revenue">Umsatz: ${formatEuro(revenue)}</div><div class="month-diff ${diff>=0?"diff-pos":"diff-neg"}">${diff>=0?"+":""}${formatEuro(diff)}</div>`;g.appendChild(d);});}
function resetYear(){if(!state.yearDays.length)return;state.yearDays.forEach(d=>{d.tours=0;d.level="none";d.notes="";});renderYearTable();renderYearKpis();renderMonthly();}
function setInfo(msg,type){const el=$("infoMsg");el.textContent=msg;el.className="info-msg"+(type?" "+type:"");}
function setButtonsDisabled(dis){["generateBtn","applyTemplateBtn","resetYearBtn"].forEach(id=>{$(id).disabled=dis;});}
function switchView(v){state.currentView=v;document.querySelectorAll(".tab-btn").forEach(b=>{b.classList.toggle("is-active",b.dataset.view===v);});document.querySelectorAll(".view").forEach(el=>{el.hidden=!el.classList.contains("view-"+v);});if(v==="year"&&state.currentYear===null)generateYear();}
window._tourApp={state,$,groupSize,duration,vorlauf,nachlauf,staffMin,wage,svFactor,bufFactor,levels,priceAdult,priceReduced,avgPrice,formatDate,formatHours,formatEuro,formatDuration,MONTH_NAMES,BUNDESLAENDER,DOW_SHORT,getMonthlyStats,renderWeek,renderYearTable,renderYearKpis,renderMonthly,DAY_KEYS,DAY_SHORT,clampInt,clampFloat,inferLevel,keyFor,parseKey,initTemplate,buildYearDays,setInfo,switchView,generateYear};
// Init
initTemplate();renderWeek();
["groupSize","tourDuration","prepTime","followTime","levelLow","levelMedium","levelHigh","hourlyWage","svRate","bufferRate","priceAdult","priceReduced"].forEach(id=>{$(id).addEventListener("input",()=>{renderWeek();if(state.yearDays.length>0){state.yearDays.forEach(d=>{d.level=inferLevel(d.tours);});state.yearDays.forEach(updateRow);renderYearKpis();renderMonthly();}});});
document.querySelectorAll("[data-bulk]").forEach(b=>{b.addEventListener("click",()=>{const v=b.dataset.bulk==="zero"?0:levelPreset(b.dataset.bulk);DAY_KEYS.forEach(k=>{state.weekTours[k]=v;});renderWeek();});});
document.querySelectorAll(".tab-btn").forEach(b=>{b.addEventListener("click",()=>switchView(b.dataset.view));});
$("generateBtn").addEventListener("click",()=>{generateYear();if(state.currentView!=="year")switchView("year");});
$("applyTemplateBtn").addEventListener("click",()=>applyTemplateToYear(true));
$("resetYearBtn").addEventListener("click",resetYear);
$("yearSelect").addEventListener("change",()=>{if(state.currentYear!==null)generateYear();});
$("stateSelect").addEventListener("change",()=>{if(state.currentYear!==null)generateYear();});
$("excludeHolidays").addEventListener("change",()=>{if(state.yearDays.length>0)applyTemplateToYear(true);});
})();
